### ISSUE TITLE
Guard nightly-only api usage (e.g. `feature(allocator_api)`) behind a feature gate

### ISSUE THREAD

**Issue by lynzrand** [LemonHX/mimalloc-rust#3]
This crate is nightly-only, but it's not stated in the ReadMe nor the main documentation (lib.rs does this). Many users use stable Rust release, and this crate should be usable in stable environment, albeit with missing features (e.g. Allocator API) instead of being completely unable to compile at all.

## Solution

Guard Allocator API usage behind a feature gate, and release a stable version with the `Allocator` trait items implemented without specifying the trait.

## Alternative solution

Write `🚧🚧🚧 This crate is Nightly Only 🚧🚧🚧` in readme.

**Comment by LemonHX** [comment]
refactor: add cfg unstable guard #4
merged
